<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LayerOne.Safeguard.Brand</RootNamespace>
    <AssemblyName>Safeguard.Brand</AssemblyName>
  </PropertyGroup>
</Project>
